version: '3.2'
services:
  mssql-database:
    build:
      context: ./mssql
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=admin@12345
      - MSSQL_PID=Express
    volumes:
      - ./mssql/sqlsystem:/var/opt/mssql/
volumes:
  sqlsystem: